baseurl = "/"
title = "Hugo Tanka Theme"
author = "Nan Xiao"
relativeurls = true
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["_files$", "_cache$"]

[params]
  sitename = "Rosie Abe's Data Stuff"

[[menu.main]]
    name = "Home"
    url = "https://rosieabe.com"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rosieabe"
    weight = 2
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/rosieabe/"
    weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/rosieabe"
    weight = 4
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
